baseurl = "https://blog.zachariasmanuel.com"
languageCode = "en-us"
title = "Zacs Blog"
MetaDataFormat = "toml"
theme = "slender"
paginate = 3
PaginatePath = "/"

[author]
    name = "Zacharias Manuel"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]

    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "white"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = "</br>"

    # Footer; Markdown accepted here.
    footer = "Copyright 2020 &copy; Zacharias Manuel"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Personal tech blog of Zacharias Manuel"
    keywords = "zac,zacharias,zacharias manuel, android, tech head, startup village, kochi, fin robotics, neyya, android head, startup, kerala, android developer, hardware startup"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    email = "mailto:zac@zachariasmanuel.com"
    github = "https://github.com/zachariasmanuel"
    #bitbucket = "url-to-your-bitbucket"
    twitter = "https://twitter.com/zachmanuel90"
    stackoverflow = "http://stackoverflow.com/users/1112879/zacharias-manuel"
    linkedin = "https://www.linkedin.com/in/zachariasmanuel"
    facebook = "https://www.facebook.com/zachariasmanuel"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    ganalytics = "UA-42601089-3"

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/"
    weight     = 0

    #[[menu.main]]
    #identifier = "about"
    #name       = "about"
    #url        = "/about/"
    #weight     = 1
